// =========================
// QUIZ QUESTIONS
// =========================
const questions = [
  {
    id: "intro",
    type: "intro",
    title: "Discover your Traveler Archetype",
    intro:
      "This isn't your average travel questionnaire. <br><br> Over the next <b>5 - 10 minutes</b>, you'll move through carefully designed sections that uncover your unique traveler archetype. A reflection of not just how you move through the world, but why. Together, we’ll touch on your values, passions, and preferences. Each question draws from principles in personality theory, behavioral psychology, cultural intelligence, and mind style to give you a result that feels as true as it is useful. <br><br> We’ll be honest, a few questions may seem random. They’re not. Every single one has a purpose, and it’ll all make sense when you get your results. Just answer from the gut and be real with yourself. The more honest you are, the more aligned your outcome will be. <br><br> By the end, you’ll not only unlock tailored destination recommendations, experiences, and insights, you'll also come away with a better understanding of yourself. How you connect. How you recharge. How you thrive. So far,  87% of travelers have said it's changed the way they travel, and helped them to push for more fulfilling experiences. So thanks for trusting us with this part of your journey. <br><br>Let's get into it.",
    button: "Let's go",
    maxScore: 0,
  },
  {
    id: "name",
    type: "text",
    label: "Please enter your first and last name",
    required: true,
    maxScore: 0,
  },
  {
    id: "ageRange",
    type: "single",
    label: "Please select your age range",
    required: true,
    options: [
      { badge: "A", text: "24 & Under" },
      { badge: "B", text: "25 - 30" },
      { badge: "C", text: "30 - 40" },
      { badge: "D", text: "40 - 50" },
      { badge: "E", text: "50 - 60" },
      { badge: "F", text: "60+" },
    ],
    maxScore: 3,
  },
  {
    id: "relationshipStatus",
    type: "select",
    label: "What is your current relationship status?",
    required: true,
    helper:
      "Understanding your current relationship status allows us to develop more intentional recommendations. Whether you’re single and ready to mingle, married and seeking romance, in a relationship and looking to deepen your connection or happily solo!",
    options: [
      "Single - Not Looking",
      "Single - Looking",
      "In a relationship",
      "Married",
      "In an open relationship",
      "Widowed",
      "Divorced",
      "Other",
    ],
    maxScore: 3,
  },
  {
    id: "gender",
    type: "select",
    label: "What is your gender?",
    required: true,
    options: ["Male", "Female", "Transgender", "Non binary", "Other"],
  },
  {
    id: "country",
    type: "text",
    label: "What country do you live in?",
    required: true,
    placeholder: "Enter your country",
    maxScore: 0,
  },
  {
    id: "stateRegion",
    type: "text",
    label: "What state/region do you live in?",
    required: true,
    helper: "This helps us provide more localized travel recommendations.",
    placeholder: "Enter your state, region, or province",
    maxScore: 0,
  },
  {
    id: "religion",
    type: "single",
    label: "What religious affiliation(s) do you identify with?",
    required: true,
    options: [
      { badge: "A", text: "Agnostic" },
      { badge: "B", text: "Atheist" },
      { badge: "C", text: "Buddhist" },
      { badge: "D", text: "Christian" },
      { badge: "E", text: "Folk/Indigenous" },
      { badge: "F", text: "Hindu" },
      { badge: "G", text: "Jain" },
      { badge: "H", text: "Jewish" },
      { badge: "I", text: "Muslim" },
      { badge: "J", text: "Shinot" },
      { badge: "K", text: "Sikh" },
      { badge: "L", text: "Spiritual" },
      { badge: "M", text: "Taoism" },
      { badge: "N", text: "Voodoo" },
      { badge: "O", text: "Yoruba" },
      { badge: "P", text: "Other" },
    ],
    maxScore: 4,
  },
  {
    id: "languages",
    type: "multiselect",
    label: "What languages do you speak? Select all that may apply.",
    required: true,
    options: [
      "Arabic",
      "Bengali",
      "Cantonese",
      "Dutch",
      "English",
      "Farsi",
      "French",
      "German",
      "Greek",
      "Hausa",
      "Hebrew",
      "Hindi",
      "Igbo",
      "Italian",
      "Japanese",
      "Korean",
      "Mandarin",
      "Portuguese",
      "Punjabi",
      "Russian",
      "Spanish",
      "Swahili",
      "Tagalog",
      "Thai",
      "Turkish",
      "Urdu",
      "Vietnamese",
      "Yoruba",
      "Other",
    ],
    maxScore: 4,
  },
  {
    id: "personalityType",
    type: "scale",
    label: "What is your personality type?",
    required: true,
    min: 1,
    max: 10,
    leftLabel: "Introvert",
    midLabel: "Ambivert",
    rightLabel: "Extravert",
    maxScore: 3,
  },
  {
    id: "values",
    type: "tag-multiselect",
    label:
      "What factors are most important to you when meeting new people? Select all that may apply.",
    required: true,
    options: [
      { text: "Age", color: "option-pink" },
      { text: "Availability", color: "option-yellow" },
      { text: "Class", color: "option-yellow" },
      { text: "Cultural background", color: "option-green" },
      { text: "Education level", color: "option-blue" },
      { text: "Ethnicity", color: "option-purple" },
      { text: "Gender Identity", color: "option-pink" },
      { text: "Hobbies", color: "option-blue" },
      { text: "Hometown", color: "option-orange" },
      { text: "Income", color: "option-yellow" },
      { text: "Language fluency", color: "option-yellow" },
      { text: "Moral values", color: "option-green" },
      { text: "Music taste", color: "option-blue" },
      { text: "Occupation", color: "option-purple" },
      { text: "Political affiliation", color: "option-purple" },
      { text: "Preferred social settings", color: "option-green" },
      { text: "Religious affiliation", color: "option-orange" },
      { text: "Sense of humour", color: "option-orange" },
      { text: "Sexual orientation", color: "option-yellow" },
      { text: "Substance use", color: "option-green" },
    ],
    maxScore: 0,
  },
  {
    id: "humour",
    type: "single",
    label: "How important to you is... Humour",
    required: true,
    options: [
      { badge: "A", text: "A good sense of humour is essential" },
      { badge: "B", text: "I like laughing occasionally" },
      { badge: "C", text: "I don't mind people with no sense of humour" },
      { badge: "D", text: "I don't find much funny" },
    ],
    maxScore: 3,
  },
  {
    id: "loneliness",
    type: "scale",
    label: "How often do you feel lonely?",
    required: true,
    min: 1,
    max: 10,
    leftLabel: "Never",
    midLabel: "Occasionally",
    rightLabel: "Every day",
    maxScore: 0,
  },
  {
    id: "groupSpeaking",
    type: "scale",
    label: "How often are you the one talking in group settings?",
    required: true,
    min: 1,
    max: 10,
    leftLabel: "I only Listen",
    rightLabel: "Primary speaker",
    maxScore: 0,
  },
  {
    id: "adviceStyle",
    type: "scale",
    label: "Does your advice tend to be more logical or emotional?",
    required: true,
    min: 1,
    max: 10,
    leftLabel: "Pure logic",
    midLabel: "A bit of both",
    rightLabel: "Right from the heart",
    maxScore: 0,
  },
  {
    id: "sleepSchedule",
    type: "single",
    label: "Are you a night owl or early bird?",
    required: true,
    options: [
      { badge: "A", text: "I'm nocturnal" },
      { badge: "B", text: "I'm an early riser" },
    ],
    maxScore: 0,
  },
  // {
  //   id: "values",
  //   type: "tag-multiselect",
  //   label:
  //     "What factors are most important to you when meeting new people? Select all that may apply.",
  //   required: true,
  //   options: [
  //     { text: "Age", color: "option-pink" },
  //     { text: "Availability", color: "option-yellow" },
  //     { text: "Class", color: "option-yellow" },
  //     { text: "Cultural background", color: "option-green" },
  //     { text: "Education level", color: "option-blue" },
  //     { text: "Ethnicity", color: "option-purple" },
  //     { text: "Gender Identity", color: "option-pink" },
  //     { text: "Hobbies", color: "option-blue" },
  //     { text: "Hometown", color: "option-orange" },
  //     { text: "Income", color: "option-yellow" },
  //     { text: "Language fluency", color: "option-yellow" },
  //     { text: "Moral values", color: "option-green" },
  //     { text: "Music taste", color: "option-blue" },
  //     { text: "Occupation", color: "option-purple" },
  //     { text: "Political affiliation", color: "option-purple" },
  //     { text: "Preferred social settings", color: "option-green" },
  //     { text: "Religious affiliation", color: "option-orange" },
  //     { text: "Sense of humour", color: "option-orange" },
  //     { text: "Sexual orientation", color: "option-yellow" },
  //     { text: "Substance use", color: "option-green" },
  //   ],
  //   maxScore: 0,
  // },
  {
    id: "change",
    type: "single",
    label: "How important to you is... Change",
    required: true,
    options: [
      { badge: "A", text: "I hate change" },
      { badge: "B", text: "I prefer things the way they are" },
      { badge: "C", text: "I can adjust to some change" },
      { badge: "D", text: "I like variation" },
      { badge: "E", text: "I love constant change" },
    ],
    maxScore: 0,
  },
  {
    id: "comfort",
    type: "single",
    label: "How important to you is... Comfort",
    required: true,
    options: [
      { badge: "A", text: "I like what i like" },
      { badge: "B", text: "Some of the familiar, some of the new" },
      { badge: "C", text: "Throw me in the deep end" },
    ],
    maxScore: 0,
  },
  {
    id: "family",
    type: "single",
    label: "How important to you is... Family",
    required: true,
    options: [
      { badge: "A", text: "I'm not a big family person" },
      { badge: "B", text: "I love my family in doses" },
      { badge: "C", text: "Im very family oriented" },
    ],
    maxScore: 0,
  },
  {
    id: "appearance",
    type: "single",
    label: "How important to you is... My appearance",
    required: true,
    options: [
      { badge: "A", text: "I don't care what i look like" },
      { badge: "B", text: "Im make sure i'm presentable" },
      { badge: "C", text: "I take great pride in my appearance" },
    ],
    maxScore: 0,
  },
  {
    id: "nonConformity",
    type: "single",
    label: "How important to you is... Non conformity",
    required: true,
    options: [
      { badge: "A", text: "I am 100% myself everywhere i go" },
      { badge: "B", text: "I'm fluid depending on the situation" },
      { badge: "C", text: "I like to blend in with others" },
    ],
    maxScore: 0,
  },
  {
    id: "physicalAttraction",
    type: "single",
    label: "How important to you is... Physical Attraction",
    required: true,
    options: [
      { badge: "A", text: "I love a bit of eye candy" },
      { badge: "B", text: "Looks are important but not everything" },
      { badge: "C", text: "I don't care about looks" },
    ],
    maxScore: 0,
  },
  {
    id: "buildingWealth",
    type: "single",
    label: "How important to you is... Building Wealth",
    required: true,
    options: [
      { badge: "A", text: "I save and invest like my life depends on it" },
      { badge: "B", text: "I save some and spend some" },
      { badge: "C", text: "Life is short, so i spend as i please" },
      { badge: "D", text: "I spend what i need to save me time" },
    ],
    maxScore: 0,
  },
  {
    id: "spirituality",
    type: "single",
    label: "How important to you is... Spirituality",
    required: true,
    options: [
      { badge: "A", text: "I believe in one true religion" },
      { badge: "B", text: "I create my own practices and beliefs" },
      { badge: "C", text: "I believe in meditation and mindfulness" },
      { badge: "D", text: "I believe in science" },
      { badge: "E", text: "I don't believe in anything" },
    ],
    maxScore: 0,
  },
  {
    id: "creativity",
    type: "single",
    label: "How important to you is... Creativity",
    required: true,
    options: [
      { badge: "A", text: "I feel lost when im not creating" },
      { badge: "B", text: "I like being creative sometimes" },
      { badge: "C", text: "I'm not creative at all" },
    ],
    maxScore: 0,
  },
  {
    id: "friendships",
    type: "single",
    label: "How important to you is... Friendships",
    required: true,
    options: [
      { badge: "A", text: "I make friends everywhere i go" },
      { badge: "B", text: "I love my friends" },
      { badge: "C", text: "I wish i had more friends" },
      { badge: "D", text: "I find it hard to make friends" },
      { badge: "E", text: "I prefer to be by myself" },
    ],
    maxScore: 0,
  },
  {
    id: "livingWell",
    type: "single",
    label: "How important to you is... Living well",
    required: true,
    options: [
      { badge: "A", text: "Health and wellness are everything" },
      { badge: "B", text: "Investing in my spiritual healthy is vital" },
      { badge: "C", text: "The simple things keep me happy" },
      { badge: "D", text: "Love, laugh, live" },
      { badge: "E", text: "I live to pamper myself" },
      { badge: "F", text: "Discovering new things makes me feel alive" },
    ],
    maxScore: 0,
  },
  {
    id: "foreignEnvironments",
    type: "single",
    label:
      "How comfortable are you with navigating foreign environments on your own?",
    required: true,
    options: [
      { badge: "A", text: "Very comfortable, I love to explore independently" },
      { badge: "B", text: "Comfortable with some help or guidance" },
      {
        badge: "C",
        text: "Not very comfortable, I prefer guided tours or group",
      },
    ],
    maxScore: 0,
  },
  {
    id: "worldView",
    type: "single",
    label: "How do you view the world around you?",
    required: true,
    options: [
      {
        badge: "A",
        text: "I see it as a place full of adventure waiting to be explored",
      },
      {
        badge: "B",
        text: "I see it as a complex place, and I want to understand more about it",
      },
      {
        badge: "C",
        text: "I see it as overwhelming, and I prefer more simple, curated experiences",
      },
      { badge: "D", text: "I live in my own world" },
    ],
    maxScore: 0,
  },
  {
    id: "biggestFear",
    type: "single",
    label: "What is your biggest fear when traveling?",
    required: true,
    options: [
      { badge: "A", text: "Getting lost in an unfamiliar place" },
      { badge: "B", text: "Experiencing culture shock" },
      { badge: "C", text: "Missing out on memorable experiences" },
      { badge: "D", text: "Feeling isolated or traveling alone" },
      { badge: "E", text: "Not finding activities that truly interest me" },
      { badge: "F", text: "Getting sick or injured whilst abroad" },
      { badge: "G", text: "Missing my flight or connections" },
      { badge: "H", text: "Losing my luggage or important belongings" },
      { badge: "I", text: "Getting into legal trouble" },
      { badge: "J", text: "Running out of money or going over budget" },
      { badge: "K", text: "Not feeling safe or secure during the trip" },
      {
        badge: "L",
        text: "Not being able to communicate due to language barriers",
      },
    ],
    maxScore: 0,
  },
  {
    id: "comfortZone",
    type: "single",
    label:
      "How open are you to traveling to places outside of your comfort zone?",
    required: true,
    options: [
      { badge: "A", text: "I prefer sticking to what I know" },
      { badge: "B", text: "I'd consider it with an experienced guide" },
      { badge: "C", text: "Sometimes, but I'm open to new things" },
      { badge: "D", text: "I thrive in unfamiliar environments" },
    ],
    maxScore: 0,
  },
  {
    id: "challengeReaction",
    type: "single",
    label:
      "When experiencing challenges or unexpected plan changes, how do you react?",
    required: true,
    options: [
      {
        badge: "A",
        text: "I stay calm, embrace the change and start problem solving",
      },
      { badge: "B", text: "I don't mind a little chaos, i find it exciting" },
      { badge: "C", text: "I adapt but it can be a little stressful" },
      { badge: "D", text: "I get upset and require immediate help navigating" },
    ],
    maxScore: 0,
  },
  {
    id: "problemSolving",
    type: "single",
    label: "How do you solve a problem you've never seen before?",
    required: true,
    options: [
      {
        badge: "A",
        text: "Research and gather as much information as possible",
      },
      { badge: "B", text: "Think outside the box and try a creative approach" },
      { badge: "C", text: "Look at how others have solved similar problems" },
      { badge: "D", text: "Follow your instincts and adjust as you go" },
      { badge: "E", text: "Create a long-term plan with backup options" },
    ],
    maxScore: 0,
  },
  {
    id: "firstNotice",
    type: "single",
    label: "When you arrive in a new place, what do you notice first?",
    required: true,
    options: [
      {
        badge: "A",
        text: "The small details that seem out of place or unusual",
      },
      {
        badge: "B",
        text: "The overall vibe, colors, or visual feel of the location",
      },
      {
        badge: "C",
        text: "What needs to be done right away (e.g: checking in, finding essentials)",
      },
      {
        badge: "D",
        text: "How people are behaving, interacting, or treating others",
      },
      {
        badge: "E",
        text: "How everything connects, the layout, culture, and purpose of the space",
      },
    ],
    maxScore: 0,
  },
  {
    id: "destinationValues",
    type: "single",
    label: "What do you value the most when choosing a travel destination?",
    required: true,
    options: [
      { badge: "A", text: "Sustainability & supporting the local region" },
      { badge: "B", text: "Authenticity" },
      { badge: "C", text: "Comfort and Luxury" },
      { badge: "D", text: "Relaxation & Wellness" },
      { badge: "E", text: "Adventure and excitement" },
      { badge: "F", text: "Personal Growth" },
      { badge: "G", text: "Learning about new cultures" },
      { badge: "H", text: "Making memories & bonding with others" },
      { badge: "I", text: "Finding love" },
      { badge: "J", text: "Other: Please state" },
    ],
    maxScore: 0,
  },
  {
    id: "travelExperience",
    type: "single",
    label: "Which of the following travel experiences sounds most like you?",
    required: true,
    options: [
      {
        badge: "A",
        text: "Trekking through remote mountains or forests off the beaten path",
      },
      { badge: "B", text: "An exclusive cocktail party on a yacht" },
      {
        badge: "C",
        text: "Staying on a private island luxury villa with personal staff",
      },
      {
        badge: "D",
        text: "Joining a volunteer project that makes a difference",
      },
      {
        badge: "E",
        text: "Walking ancient city ruins filled with history and stories",
      },
      {
        badge: "F",
        text: "Dancing at a vibrant festival or underground music event",
      },
      {
        badge: "G",
        text: "Spending time at a wellness retreat focused on mindfulness",
      },
      {
        badge: "H",
        text: "An all inclusive, kid friendly adventure park with spa and entertainment facilities for the adults",
      },
      {
        badge: "I",
        text: "Taking pictures at the most well known attractions",
      },
      { badge: "J", text: "Sailing, surfing and snorkeling with turtles." },
      {
        badge: "K",
        text: "A locally hosted art class and traditionally cooked dinner in Italy",
      },
      { badge: "L", text: "There's nothing I haven't done!" },
    ],
    maxScore: 0,
  },
  {
    id: "accommodationPreference",
    type: "single",
    label: "When it comes to accommodations, what do you prefer?",
    required: true,
    options: [
      { badge: "A", text: "Luxury hotels and homes" },
      { badge: "B", text: "Unique boutique stays or eco-lodges" },
      { badge: "C", text: "All-Inclusive resorts" },
      { badge: "D", text: "Homestays or immersive local guesthouses" },
      { badge: "E", text: "Group hostels or campsites" },
      { badge: "F", text: "Vacation rentals & villas" },
    ],
    maxScore: 0,
  },
  {
    id: "climatePreference",
    type: "single",
    label: "What type of climate do you prefer when traveling?",
    required: true,
    options: [
      { badge: "A", text: "Warm and tropical" },
      { badge: "B", text: "Cold and snowy" },
      { badge: "C", text: "Cool and temperate" },
      { badge: "D", text: "Dry arid deserts" },
      {
        badge: "E",
        text: "I enjoy different climates depending on the activity",
      },
    ],
    maxScore: 0,
  },
  {
    id: "tripPace",
    type: "single",
    label: "What is the ideal pace of your trip?",
    required: true,
    options: [
      { badge: "A", text: "Keep me busy, i like following a set itinerary" },
      {
        badge: "B",
        text: "I plan a few things, but leave time to be flexible",
      },
      { badge: "C", text: "I like to browse through vetted recommendations" },
      { badge: "D", text: "I prefer to be spontaneous and explore freely" },
    ],
    maxScore: 0,
  },
  {
    id: "travelCompanions",
    type: "single",
    label: "How do you feel about traveling with family or friends?",
    required: true,
    options: [
      { badge: "A", text: "I love it, it creates great memories" },
      { badge: "B", text: "I prefer to travel with people i don't know yet" },
      {
        badge: "C",
        text: "I've never traveled with anyone before, but i'm open to it",
      },
      { badge: "D", text: "I enjoy it sometimes but also value my alone time" },
      { badge: "E", text: "I prefer traveling solo" },
    ],
    maxScore: 0,
  },
  {
    id: "priorityRating",
    type: "slider-multiselect",
    label: "Rate in order of importance",
    required: true,
    options: [
      {
        text: "Flight & Transport",
        min: 1,
        max: 10,
        leftLabel: "1",
        rightLabel: "10",
      },
      {
        text: "Experiences",
        min: 1,
        max: 10,
        leftLabel: "1",
        rightLabel: "10",
      },
      {
        text: "Accommodation",
        min: 1,
        max: 10,
        leftLabel: "1",
        rightLabel: "10",
      },
    ],
    maxScore: 0,
  },
  {
    id: "spendingPreferences",
    type: "slider-multiselect",
    label: "Select your typical spend for each category",
    required: true,
    options: [
      {
        text: "Accommodation",
        min: 500,
        max: 10000,
        leftLabel: "$500",
        rightLabel: "$10,000+",
      },
      {
        text: "Flights & Transport",
        min: 500,
        max: 10000,
        leftLabel: "$500",
        rightLabel: "$10,000+",
      },
      {
        text: "Experiences",
        min: 500,
        max: 10000,
        leftLabel: "$500",
        rightLabel: "$10,000+",
      },
      {
        text: "Food & Drink",
        min: 500,
        max: 10000,
        leftLabel: "$500",
        rightLabel: "$10,000+",
      },
      {
        text: "Spending money",
        min: 500,
        max: 10000,
        leftLabel: "$500",
        rightLabel: "$10,000+",
      },
    ],
    maxScore: 0,
  },
  {
    id: "outro",
    type: "outro",
    title: "Almost Done",
    intro:
      "You’ll also gain access to our exclusive community and receive occasional, thoughtfully curated insights, event invitations, and travel inspiration from Kior Travel. By confirming, you agree to join our mailing list. You can update your preferences or unsubscribe at any time. We respect your privacy and never share your details with third parties.",
    button: "I confirm. Send me my travel archetype report",
    maxScore: 0,
  },
  {
    id: "email",
    type: "text",
    label: "Please enter your email",
    required: true,
    maxScore: 0,
  },
];
